http:
  port: 4000
admin:
  port: 9876
  host: localhost

apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  users:
    host: localhost
    paths:
      - "/api/auth/*"
  chat:
    host: localhost
    paths:
      - "/api/chat/*"
  favorites:
    host: localhost
    paths:
      - "/api/favorites/*"

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService:
    url: "http://localhost:5001"
  chatService:
    url: "http://localhost:5002"
  favoritesService:
    url: "http://localhost:5003"

policies:
  - jwt
  - proxy

pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  api-auth:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true

  api-chat:
    apiEndpoints:
      - chat
    policies:
      - jwt:
          - action:
              secretOrPublicKey: "tu_secreto_super_seguro"  # ✅ Usa la variable de entorno
              checkAuthorization: true
      - proxy:
          - action:
              serviceEndpoint: chatService
              changeOrigin: true
              headers:  # ✅ Asegura que pase el token de autorización al servicio de chat
                Authorization: "[[req.headers.authorization]]"

  api-favorites:
    apiEndpoints:
      - favorites
    policies:
      - jwt:
          - action:
              secretOrPublicKey: "tu_secreto_super_seguro"  # ✅ Usa la variable de entorno
              checkAuthorization: true
      - proxy:
          - action:
              serviceEndpoint: favoritesService
              changeOrigin: true
              headers:  # ✅ Asegura que pase el token de autorización al servicio de favoritos
                Authorization: "[[req.headers.authorization]]"