http:
  port: 4000
admin:
  port: 9876
  host: localhost

apiEndpoints:
  users:
    host: localhost
    paths:
      - "/api/auth/*"
  chat:
    host: localhost
    paths:
      - "/api/chat/*"
  favorites:
    host: localhost
    paths:
      - "/api/favorites/*"
  music:  # 🔥 Nuevo microservicio de música
    host: localhost
    paths:
      - "/api/music/*"

serviceEndpoints:
  userService:
    url: "http://localhost:5001"
  chatService:
    url: "http://localhost:5002"
  favoritesService:
    url: "http://localhost:5003"
  musicService:  # 🔥 Nuevo microservicio de música
    url: "http://localhost:5004"

policies:
  - proxy

pipelines:
  api-auth:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true

  api-chat:
    apiEndpoints:
      - chat
    policies:
      - proxy:
          - action:
              serviceEndpoint: chatService
              changeOrigin: true

  api-favorites:
    apiEndpoints:
      - favorites
    policies:
      - proxy:
          - action:
              serviceEndpoint: favoritesService
              changeOrigin: true

  api-music:  # 🔥 Nuevo pipeline para el microservicio de música
    apiEndpoints:
      - music
    policies:
      - proxy:
          - action:
              serviceEndpoint: musicService
              changeOrigin: true
